#!/bin/bash

while [[ $# -gt 0 ]]; do
    case "$1" in
        -g|--gitlab-url)
            echo export GITLAB_URL="$2"
            export GITLAB_URL="$2"
            shift 2
            ;;
        -i|--project-id)
            export GITLAB_PROJECT_ID="$2"
            shift 2
            ;;
        -u|--tf-username)
            export TF_USERNAME="$2"
            shift 2
            ;;
        -p|--tf-password)
            export TF_PASSWORD="$2"
            shift 2
            ;;
        -s|--tf-state-name)
            export TF_STATE_NAME="$2"
            shift 2
            ;;
        -h|--help)
            echo "Usage: source $0 [-g|--gitlab-url GITLAB_URL] [-i|--project-id GITLAB_PROJECT_ID] [-s|--tf-state-name TF_STATE_NAME] [-u|--tf-username TF_USERNAME] [-p|--tf-password TF_PASSWORD]"
            break
            ;;
        *)
            echo "Error: Unknown parameter: $1"
            break
            ;;
    esac
done
